-- Database Create
CREATE DATABASE user_management;

-- Oluşturulmuş database seçmek
USE user_management;

-- user adında bir tablo oluştur
-- Kullanıcı tablosu oluştur
CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE
);

-- Örnek veri ekleme
INSERT INTO users (username, password, email) VALUES ('admin', '123456', 'admin@example.com');
INSERT INTO users (username, password, email) VALUES ('user1', 'password1', 'user1@example.com');
INSERT INTO users (username, password, email) VALUES ('user2', 'password2', 'user2@example.com');


-- Insert
--INSERT INTO users(username,password,email) VALUES ("Hamit","123456","hamitmizrak@gmail.com");
--
---- Select
--select * FROM users;
--
---- Find User
--SELECT  *  FROM users WHERE username="Hamit" AND "123456";
--
---- Update
--UPDATE users SET username="Hamit44", password="12345644", email="hamitmizrak@gmail.com44" WHERE id=1;
--
---- delete
--DELETE FROM users  WHERE id=1;

-- ###################################################################################################################

CREATE TABLE receipts (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- H2 için AUTO_INCREMENT yerine IDENTITY kullanıyoruz.
    receipt_number VARCHAR(50) NOT NULL UNIQUE,
    receipt_date DATE NOT NULL,
    tax_number VARCHAR(20) NOT NULL,
    company_name VARCHAR(100) NOT NULL,
    customer_name VARCHAR(100) NOT NULL,
    description TEXT,
    created_by VARCHAR(100) NOT NULL,
    account_code VARCHAR(50) NOT NULL,

    -- ENUM yerine CHECK constraint ile değerleri sınırlıyoruz
    receipt_type VARCHAR(20) NOT NULL CHECK (receipt_type IN ('Ödeme', 'Tahsilat', 'Masraf', 'Gelir')),
    amount DECIMAL(10,2) NOT NULL,
    vat_rate DECIMAL(5,2) NOT NULL,
    total_amount DECIMAL(10,2) NOT NULL,

    -- ENUM yerine CHECK constraint
    payment_type VARCHAR(20) NOT NULL CHECK (payment_type IN ('Nakit', 'Kredi Kartı', 'Havale', 'Çek')),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- ###################################################################################################################


